"""Send a daily HTML-email summary via Resend, in Newsprint design.

Drives off two env vars (set as repo secrets):
  - RESEND_API_KEY     — get one at https://resend.com (free 3000/mo)
  - NOTIFY_EMAIL_TO    — recipient address(es), comma-separated

Optional:
  - NOTIFY_EMAIL_FROM  — default 'KS China Tracker <onboarding@resend.dev>'.

Visual rules echo the Pages site / banner SVG exactly:
  - Newsprint off-white #F9F9F7 paper, ink black #111111
  - Playfair Display 900 nameplate centered, Lora italic dek
  - Vol. 1 / No. N edition number, BEIJING EDITION metadata bar
  - Ornamental ✦ ✦ ✦ section dividers
  - JetBrains Mono for all numbers, Inter for labels
  - Sharp 0-radius corners, 1px solid borders, no shadows

Run locally:
  python -m scraper.email_notify --dry-run    # writes preview to data/.tmp/
  python -m scraper.email_notify              # POST to Resend
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import sys
import time
from pathlib import Path

import httpx

from .momentum import conversion_per_watcher, projected_total
from .notify import (
    LATEST_URL,
    PAGES_URL,
    PROJECTS,
    REPO_ROOT,
    fmt_int,
    fmt_usd,
    get_summary_data,
)

RESEND_API_URL = "https://api.resend.com/emails"

from ._common import edition_number  # noqa: E402  shared edition number

# ── Newsprint design tokens (mirror site CSS) ────────────────────
PAPER = "#F9F9F7"
INK = "#111111"
RED = "#CC0000"
MUTED = "#E5E5E0"
N400 = "#A3A3A3"
N500 = "#737373"
N600 = "#525252"
N700 = "#404040"

SERIF = "'Playfair Display', 'Times New Roman', 'Songti SC', serif"
BODY = "'Lora', Georgia, 'Songti SC', serif"
SANS = "'Inter', 'Helvetica Neue', 'PingFang SC', sans-serif"
MONO = "'JetBrains Mono', 'Courier New', monospace"


def _esc(s: str) -> str:
    return (str(s or "").replace("&", "&amp;")
            .replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def _render_emergency_banner(curr: dict) -> str:
    """If today's snapshot was built via emergency_refresh (because the
    discover crawl was CF-blocked), prepend a small honest banner
    explaining that today's edition uses yesterday's project catalog
    refreshed via GraphQL.
    """
    info = curr.get("_emergency_refresh")
    if not info:
        return ""
    refreshed = info.get("projects_refreshed", 0)
    state_changes = info.get("state_changes_detected", 0)
    return f'''
        <!-- Emergency refresh banner — KS rate-limited today, this is a
             best-effort refresh from yesterday's catalog -->
        <div style="margin:0 0 18px;padding:14px 18px;
                    background:{MUTED};border-left:4px solid {RED};
                    font-family:{SANS};font-size:12px;line-height:1.5;color:{N700}">
          <div style="font-family:{MONO};font-size:10px;font-weight:700;
                      color:{RED};letter-spacing:.2em;text-transform:uppercase;
                      margin-bottom:6px">
            🛠️ ABOUT TODAY'S EDITION
          </div>
          <div>
            Kickstarter 今天对 discover 入口做了强反爬，常规爬取被拦在源头。
            本期编辑使用<strong>昨天发现的 {refreshed} 个项目目录</strong>，
            通过 GraphQL <strong>实时刷新</strong>了今天的 watchers / pledged /
            backers / state 数据——{state_changes} 个项目状态变化已捕获。
            <strong>今天新发现的项目可能缺失</strong>，明早 cron 恢复正常时
            会补齐。
          </div>
        </div>'''


def _load_editor_drafts() -> dict | None:
    """Read data/.editor_drafts.json if present. Generated by
    scripts/draft_editor_note.py (run by cron when DEEPSEEK_API_KEY is set).

    File is gitignored — it's an artifact, not source data.
    Returns None if missing or unparseable (Beta section then hidden).
    """
    p = REPO_ROOT / "data" / ".editor_drafts.json"
    if not p.exists():
        return None
    try:
        d = json.loads(p.read_text(encoding="utf-8"))
        if not isinstance(d.get("drafts"), list) or not d["drafts"]:
            return None
        return d
    except Exception:
        return None


def _render_editor_drafts_beta(drafts_data: dict | None) -> str:
    """Render the bottom-of-email Beta section: collapsible <details> with
    the 3 LLM-drafted editor's note candidates inside.

    Hidden by default — reader clicks the summary to expand. In clients that
    don't support <details> (Outlook desktop), the candidates render inline
    with the BETA badge still clearly marked, so the experiment is still
    legible just not collapsed."""
    if not drafts_data:
        return ""
    drafts = drafts_data.get("drafts") or []
    if not drafts:
        return ""

    model = _esc(drafts_data.get("model") or "?")
    gen_at = _esc(drafts_data.get("generated_at") or "")

    cards: list[str] = []
    for d in drafts:
        idx = d.get("index", "?")
        temp = d.get("temp", "?")
        text = _esc(d.get("text") or "(空)")
        warns = d.get("warnings") or []
        status_label = (
            "lint 干净"
            if not warns
            else f"lint 警告: {' / '.join(_esc(w) for w in warns)}"
        )
        cards.append(f'''
        <div style="margin:18px 0;padding:14px 16px;
                    border-left:3px solid {INK};background:{PAPER}">
          <div style="font-family:{MONO};font-size:10px;letter-spacing:.18em;
                      color:{N500};text-transform:uppercase;margin-bottom:8px">
            候选 #{idx} · temp={temp} · {status_label}
          </div>
          <div style="font-family:{BODY};font-size:14px;color:{INK};
                      line-height:1.65;white-space:pre-wrap">{text}</div>
        </div>''')

    return f'''
        <!-- BETA: AI-drafted editor's notes (collapsible, hidden by default) -->
        <div style="margin-top:36px;padding:16px 18px;
                    border:1px dashed {N400};background:{MUTED}">
          <details>
            <summary style="cursor:pointer;font-family:{MONO};font-size:11px;
                            letter-spacing:.22em;color:{RED};
                            text-transform:uppercase;font-weight:700;
                            outline:none;list-style:none">
              🧪 BETA · 点击展开 · 本日 3 个 AI 起草的编辑笔记
            </summary>
            <div style="margin-top:16px;padding-top:14px;
                        border-top:1px solid {N400};font-family:{BODY};
                        font-size:13px;color:{N700};line-height:1.6">
              <p style="margin:0 0 12px;font-style:italic">
                实验中。我们让 LLM 起草本日编辑笔记，要求覆盖宏观切片 +
                具体产品的"结构性怪点"。3 个候选用不同 temperature
                生成（0.7 / 0.85 / 0.95），质量参差。
                <strong>不会进入正式邮件正文</strong>——只在这个折叠区供你审。
                想给反馈？回这封邮件说一句"喜欢 #N"或者"哪个最像主编笔记"就行。
              </p>
              <p style="margin:0 0 14px;font-family:{MONO};font-size:10px;
                        letter-spacing:.12em;color:{N500};text-transform:uppercase">
                Model: {model} · Generated: {gen_at}
              </p>
              {''.join(cards)}
            </div>
          </details>
        </div>'''


def _load_highlights_zh() -> dict[str, list[str]]:
    """Curated 4-bullet Chinese highlights (same source as social.py)."""
    f = REPO_ROOT / "data" / "highlights_zh.json"
    if not f.exists():
        return {}
    try:
        raw = json.loads(f.read_text(encoding="utf-8"))
        return {k: v for k, v in raw.items()
                if isinstance(v, list) and not k.startswith("_")}
    except Exception:
        return {}


def _detail_card(p: dict, *, kind: str, hl_map: dict, rank: int) -> str:
    """Top-3 detail card for email — KS hero image + brand line + Chinese
    highlight bullets + big metric. Visual rules per user spec:
      - product image colors must NOT be filtered
      - 4:3 container with object-fit:contain so the product is never cropped
    """
    image_url = p.get("image_url") or ""
    title = _esc(p.get("title") or "(untitled)")
    blurb_zh = _esc(p.get("blurb_zh") or "")
    url = _esc(p.get("url") or "#")
    brand = _esc(p.get("matched_brand_zh") or p.get("matched_brand") or p.get("creator_name") or "")
    country = _esc(p.get("country") or "")
    star = (f'<span style="display:inline-block;background:{RED};color:{PAPER};'
            f'font-family:{SANS};font-size:9px;font-weight:700;letter-spacing:.2em;'
            f'text-transform:uppercase;padding:2px 6px;margin-right:6px;'
            f'vertical-align:2px">✦ KS PICK</span>'
           ) if p.get("project_we_love") else ""

    highlights = hl_map.get(p.get("pathname")) or []
    if not highlights and p.get("blurb"):
        # Fall back to splitting English blurb on '|' so empty entries
        # in highlights_zh.json still produce something readable.
        highlights = [s.strip() for s in p["blurb"].split("|") if s.strip()][:4]
    bullets = "".join(
        f"""<li style="margin:6px 0;font-family:{BODY};font-size:13.5px;line-height:1.5;
              color:{INK};list-style:none;padding-left:18px;position:relative">
          <span style="position:absolute;left:0;color:{RED};font-weight:900">▸</span>
          {_esc(h)}</li>"""
        for h in highlights[:4]
    )

    if kind == "prelaunch":
        big_value = fmt_int(p.get("followers"))
        big_label = "WATCHERS · 关注"
        big_color = RED
    else:
        big_value = fmt_usd(p.get("pledged_usd"))
        big_label = f"{fmt_int(p.get('backers'))} BACKERS"
        big_color = INK

    # Price line — render right after the brand·country row when present
    price_line = ""
    if p.get("min_pledge_usd"):
        price_line = (
            f'<div style="font-family:{MONO};font-size:12px;font-weight:700;color:{INK};'
            f'letter-spacing:.04em;margin-bottom:8px">'
            f'起步价 · <span style="color:{RED}">{fmt_usd(p.get("min_pledge_usd"))}</span>'
            f'</div>'
        )

    img_block = (
        f'<img src="{image_url}" width="240" height="180" '
        f'style="display:block;width:240px;height:180px;object-fit:contain;'
        f'background:{PAPER};border:1px solid {INK}" alt=""/>'
        if image_url else
        f'<div style="width:240px;height:180px;background:{MUTED};'
        f'border:1px solid {INK}"></div>'
    )

    return f'''
    <table role="presentation" cellspacing="0" cellpadding="0" border="0"
           style="width:100%;margin:18px 0;border-top:1px solid {INK};
                  border-collapse:collapse">
      <tr>
        <td style="padding:18px 0 0;width:240px;vertical-align:top">
          {img_block}
          <div style="text-align:center;margin-top:6px;font-family:{SERIF};
                      font-size:24px;font-weight:900;color:{INK};letter-spacing:-.5px">
            No. {rank:02d}</div>
        </td>
        <td style="padding:18px 0 0 18px;vertical-align:top">
          <div style="font-family:{MONO};font-size:10px;font-weight:700;color:{N500};
               letter-spacing:.18em;text-transform:uppercase;margin-bottom:6px">
            {star}{brand} &nbsp;·&nbsp; {country}</div>
          {price_line}
          <a href="{url}" style="text-decoration:none;color:{INK};
             font-family:{SERIF};font-size:18px;font-weight:700;line-height:1.2;
             letter-spacing:-.3px;display:block">{title}</a>
          <div style="margin-top:6px;font-family:{BODY};font-style:italic;
               font-size:13px;color:{N700};line-height:1.4">{blurb_zh}</div>
          <ul style="list-style:none;padding:0;margin:10px 0 0">{bullets}</ul>
          <div style="margin-top:10px">
            <span style="font-family:{MONO};font-size:24px;font-weight:700;
                  color:{big_color};letter-spacing:-.3px">{big_value}</span>
            <span style="margin-left:8px;font-family:{SANS};font-size:9px;
                  font-weight:700;color:{N500};letter-spacing:.2em">{big_label}</span>
          </div>
        </td>
      </tr>
    </table>'''


def _row(p: dict, *, kind: str) -> str:
    star = (f'<span style="color:{RED};font-family:{SERIF};font-weight:900;'
            f'margin-right:6px">✦</span>') if p.get("project_we_love") else ""
    title = _esc(p.get("title") or "(untitled)")
    blurb_zh = _esc(p.get("blurb_zh") or p.get("blurb") or "")
    url = _esc(p.get("url") or "#")
    brand = _esc(p.get("matched_brand_zh") or p.get("matched_brand") or p.get("creator_name") or "")
    country = _esc(p.get("country") or "")

    # Meta line: brand · country · [conversion ratio | projection]
    meta_parts = [x for x in (brand, country) if x]
    cpw = conversion_per_watcher(p)
    if cpw is not None and kind == "live":
        meta_parts.append(f"{fmt_usd(cpw)}/watcher")
    proj = projected_total(p) if kind == "live" else None
    if proj is not None:
        meta_parts.append(f"PROJ {fmt_usd(proj)}")
    meta = " · ".join(meta_parts)

    # Right column with optional 24h delta in red
    if kind == "prelaunch":
        main_value = f"{int(p.get('followers') or 0):,}"
        main_label = "WATCHING"
        delta = p.get("delta_followers")
        delta_str = (f' <span style="color:{RED};font-family:{MONO};font-size:13px;'
                     f'font-weight:700">+{int(delta):,}</span>') if delta and delta > 0 else ""
    else:
        main_value = fmt_usd(p.get("pledged_usd"))
        main_label = f"{int(p.get('backers') or 0):,} BACKERS"
        delta = p.get("delta_pledged_usd")
        delta_str = (f' <span style="color:{RED};font-family:{MONO};font-size:13px;'
                     f'font-weight:700">+{fmt_usd(delta)}</span>') if delta and delta > 0 else ""

    return f'''
    <tr>
      <td style="padding:14px 0;border-bottom:1px solid {INK};vertical-align:top">
        <a href="{url}" style="color:{INK};text-decoration:none;
                font-family:{SERIF};font-weight:700;font-size:17px;line-height:1.25;
                letter-spacing:-.005em">{star}{title}</a>
        <div style="margin-top:6px;font-family:{BODY};font-style:italic;font-size:13px;
                    color:{N700};line-height:1.5;text-align:justify">{blurb_zh}</div>
        <div style="margin-top:8px;font-family:{MONO};font-size:10.5px;color:{N500};
                    letter-spacing:.08em;text-transform:uppercase;font-weight:500">{meta}</div>
      </td>
      <td style="padding:14px 0 14px 14px;border-bottom:1px solid {INK};
                 vertical-align:top;text-align:right;white-space:nowrap;width:170px">
        <div style="font-family:{MONO};font-size:22px;font-weight:700;color:{INK};
                    letter-spacing:-.02em">{main_value}{delta_str}</div>
        <div style="margin-top:4px;font-family:{SANS};font-size:9.5px;font-weight:700;
                    color:{N500};letter-spacing:2px">{main_label}</div>
      </td>
    </tr>'''


def _kpi_cell(label: str, value: str, color: str = INK, *, last: bool = False) -> str:
    border = "" if last else f"border-right:1px solid {INK};"
    return f'''
    <td style="padding:24px 18px 20px;{border}vertical-align:top;text-align:left">
      <div style="font-family:{SERIF};font-weight:900;font-size:48px;letter-spacing:-1px;
                  line-height:1;color:{color}">{value}</div>
      <div style="margin-top:8px;font-family:{SANS};font-size:10px;font-weight:700;
                  color:{N500};letter-spacing:2.5px">{label}</div>
    </td>'''


def _signal_line(line: str) -> str:
    """Convert a CHANGELOG '- **Title** — detail' line into a newsprint bullet."""
    s = line.lstrip("- ").rstrip()
    if s.startswith("**"):
        end = s.find("**", 2)
        if end > 0:
            title = _esc(s[2:end])
            rest = _esc(s[end + 2:].lstrip(" —"))
            return (f'<li style="margin:10px 0;font-family:{BODY};font-size:14px;'
                    f'line-height:1.55;color:{INK};list-style:none;padding-left:18px;'
                    f'position:relative">'
                    f'<span style="position:absolute;left:0;color:{RED};font-weight:900">▸</span>'
                    f'<span style="font-family:{SERIF};font-weight:700">{title}</span>'
                    f' <span style="color:{N600};font-style:italic"> — {rest}</span>'
                    f'</li>')
    return (f'<li style="margin:10px 0;font-family:{BODY};font-size:14px;'
            f'line-height:1.55;color:{INK};list-style:none;padding-left:18px;'
            f'position:relative">'
            f'<span style="position:absolute;left:0;color:{RED};font-weight:900">▸</span>'
            f'{_esc(s)}</li>')


def build_html(curr: dict) -> tuple[str, str]:
    d = get_summary_data(curr)
    today = d["today"]
    counts = d["counts"]
    edition = edition_number()
    today_long = dt.datetime.now(dt.UTC).strftime("%A, %B %d, %Y").upper()

    subject = (
        f"[Vol. 1, No. {edition}] {today} · "
        f"{d['total']} 项 · {counts['live']} 在筹 · "
        f"{counts['prelaunch']} 未发布"
    )

    # Preheader text — the gray preview shown in inbox lists right after the
    # subject. Most clients display 60-100 chars. We pack a one-line teaser
    # with the headline live project + total raised so readers know what
    # they're getting before opening. Hidden visually via display:none +
    # 0-size; clients still read the text for the preview line.
    top_live = d["live"][0] if d["live"] else None
    top_pre = d["prelaunch"][0] if d["prelaunch"] else None
    preheader_bits = []
    if top_live:
        preheader_bits.append(
            f"今日头条：{top_live.get('title','?')[:40]} {fmt_usd(top_live.get('pledged_usd') or 0)}"
        )
    elif top_pre:
        preheader_bits.append(
            f"今日头条：{top_pre.get('title','?')[:40]} · {fmt_int(top_pre.get('followers') or 0)} watchers"
        )
    preheader_bits.append(
        f"在筹合计 {fmt_usd(d['total_live_usd'])} · ✦ KS Pick {d['pwl']}"
    )
    preheader_text = " · ".join(preheader_bits)

    # Drop cap on the lede paragraph (first paragraph after the masthead)
    lede_text = (
        f"今日（{today}）追踪到 <strong>{d['total']}</strong> 个中国背景消费硬件项目。"
        f"其中 <strong style=\"color:{RED}\">{counts['prelaunch']}</strong> 个 prelaunch、"
        f"<strong>{counts['live']}</strong> 个 live、"
        f"<strong>{counts['successful']}</strong> 个 successful。"
        f"在筹合计已筹 <strong>{fmt_usd(d['total_live_usd'])}</strong>，"
        f"中国背景置信度高 <strong>{d['high']}</strong> / {d['total']}，"
        f"获 KS Editor's Pick 标签 <strong>{d['pwl']}</strong> 项。"
    )

    # Top 3 of each track get FULL detail cards (KS hero image + brand line +
    # 4 Chinese highlights from data/highlights_zh.json + big metric). Ranks
    # 4-10 are rendered as compact text rows (no images) below.
    hl_map = _load_highlights_zh()
    pre_detail = "".join(
        _detail_card(p, kind="prelaunch", hl_map=hl_map, rank=i + 1)
        for i, p in enumerate(d["prelaunch"][:3])
    )
    live_detail = "".join(
        _detail_card(p, kind="live", hl_map=hl_map, rank=i + 1)
        for i, p in enumerate(d["live"][:3])
    )

    # Ranks 4-10 — compact text rows (uses _row helper, text-only)
    pre_rows_4_10 = "".join(_row(p, kind="prelaunch") for p in d["prelaunch"][3:10])
    live_rows_4_10 = "".join(_row(p, kind="live") for p in d["live"][3:10])
    pre_rest_html = (
        f'<table role="presentation" cellspacing="0" cellpadding="0" border="0" '
        f'style="width:100%;margin-top:6px;border-top:4px solid {INK};border-collapse:collapse">'
        f'<tbody>{pre_rows_4_10}</tbody></table>'
    ) if pre_rows_4_10 else ""
    live_rest_html = (
        f'<table role="presentation" cellspacing="0" cellpadding="0" border="0" '
        f'style="width:100%;margin-top:6px;border-top:4px solid {INK};border-collapse:collapse">'
        f'<tbody>{live_rows_4_10}</tbody></table>'
    ) if live_rows_4_10 else ""

    # ── Sleepers · algorithmic editor's picks beyond Top 10 ──────────
    from .sleepers import select_sleepers
    front_paths = set()
    front_paths.update(p.get("pathname") for p in d["prelaunch"][:10] if p.get("pathname"))
    front_paths.update(p.get("pathname") for p in d["live"][:10] if p.get("pathname"))
    front_paths.update(p.get("pathname") for p in (d.get("successful") or [])[:10] if p.get("pathname"))
    sleepers = select_sleepers(curr.get("projects") or [], front_paths, n=5)
    sleepers_html = ""
    if sleepers:
        cards = []
        for i, p in enumerate(sleepers, start=1):
            image_url = p.get("image_url") or ""
            title = _esc(p.get("title") or "(untitled)")
            url = _esc(p.get("url") or "#")
            brand = _esc(p.get("matched_brand_zh") or p.get("matched_brand") or p.get("creator_name") or "")
            country = _esc(p.get("country") or "")
            status = _esc(p.get("status") or "")
            reason = _esc(p.get("_sleeper_reason") or "")
            blurb_zh = _esc(p.get("blurb_zh") or "")
            star = (
                f'<span style="display:inline-block;background:{RED};color:{PAPER};'
                f'font-family:{SANS};font-size:9px;font-weight:700;letter-spacing:.2em;'
                f'text-transform:uppercase;padding:2px 6px;margin-right:6px;'
                f'vertical-align:2px">✦ KS PICK</span>'
            ) if p.get("project_we_love") else ""
            img_block = (
                f'<img src="{image_url}" width="180" height="135" '
                f'style="display:block;width:180px;height:135px;object-fit:contain;'
                f'background:{PAPER};border:1px solid {INK}" alt=""/>'
                if image_url else
                f'<div style="width:180px;height:135px;background:{MUTED};'
                f'border:1px solid {INK}"></div>'
            )
            cards.append(f'''
            <table role="presentation" cellspacing="0" cellpadding="0" border="0"
                   style="width:100%;margin:14px 0;border-top:1px solid {MUTED};
                          border-collapse:collapse">
              <tr>
                <td style="padding:14px 0 0;width:180px;vertical-align:top">
                  {img_block}
                </td>
                <td style="padding:14px 0 0 16px;vertical-align:top">
                  <div style="font-family:{MONO};font-size:9.5px;font-weight:700;color:{N500};
                       letter-spacing:.2em;text-transform:uppercase;margin-bottom:6px">
                    No. {i:02d} · `{status}` · {brand}{(' · ' + country) if country else ''}
                  </div>
                  <a href="{url}" style="text-decoration:none;color:{INK};
                     font-family:{SERIF};font-size:17px;font-weight:700;line-height:1.2;
                     letter-spacing:-.3px;display:block">{star}{title}</a>
                  <div style="margin-top:8px;padding:6px 10px;background:{PAPER};
                       border-left:3px solid {RED};font-family:{BODY};font-size:13px;
                       color:{INK};line-height:1.4">
                    <span style="font-family:{SANS};font-size:9.5px;font-weight:700;
                          color:{RED};letter-spacing:.18em;text-transform:uppercase;
                          margin-right:6px">WHY</span>
                    {reason}
                  </div>
                  {(f'<div style="margin-top:8px;font-family:{BODY};font-style:italic;'
                     f'font-size:13px;color:{N700};line-height:1.4">{blurb_zh}</div>')
                   if blurb_zh else ""}
                </td>
              </tr>
            </table>''')
        sleepers_html = f'''
        <div style="margin-top:48px">
          <div style="font-family:{MONO};font-size:11px;font-weight:500;color:{N500};
                      letter-spacing:2.5px;margin-bottom:6px">SECTION C</div>
          <h2 style="margin:0 0 4px;font-family:{SERIF};font-weight:900;font-size:28px;
                     letter-spacing:-.5px;color:{INK}">🌙 Sleeper Picks · Top 10 之外，有点东西的几张牌</h2>
          <p style="margin:0 0 8px;font-family:{BODY};font-style:italic;font-size:13px;color:{N500}">
            AI / 机器人 / 全球首款 / 新材料 / 单日 momentum — 命中任意一项就上榜
          </p>
          <div style="border-top:4px solid {INK}">
            {''.join(cards)}
          </div>
        </div>'''

    return subject, f'''<!DOCTYPE html>
<html lang="zh-CN">
<head><meta charset="UTF-8"><title>{_esc(subject)}</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="{_esc(subject)} — Kickstarter China Tracker daily edition.">
<link rel="canonical" href="https://ks.aldrich.fyi/editions/{today}.html">
<link rel="alternate" type="application/atom+xml" title="Kickstarter China Tracker · Atom Feed" href="https://ks.aldrich.fyi/feed.xml">
<meta property="og:type" content="article">
<meta property="og:title" content="{_esc(subject)}">
<meta property="og:url" content="https://ks.aldrich.fyi/editions/{today}.html">
<meta property="og:locale" content="zh_CN">
<!-- Per-edition social card — we re-use slide-01.png from today's carousel
     (1080×1440 portrait, generated by scraper/social.py for Xiaohongshu).
     Each archived edition gets a UNIQUE social-share preview instead of
     the static og-card.svg. -->
<meta property="og:image" content="https://ks.aldrich.fyi/social/{today}/slide-01.png">
<meta property="og:image:width" content="1080">
<meta property="og:image:height" content="1440">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="https://ks.aldrich.fyi/social/{today}/slide-01.png">
<meta property="article:published_time" content="{today}T00:00:00Z">

<!-- NewsArticle structured data — helps Google News + rich snippets pick up
     each edition as a discrete article rather than a generic webpage. -->
<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "NewsArticle",
  "headline": "{_esc(subject)}",
  "datePublished": "{today}T00:00:00Z",
  "dateModified": "{today}T00:00:00Z",
  "inLanguage": "zh-CN",
  "url": "https://ks.aldrich.fyi/editions/{today}.html",
  "publisher": {{
    "@type": "Organization",
    "name": "Kickstarter China Tracker",
    "url": "https://ks.aldrich.fyi/"
  }},
  "author": {{
    "@type": "Person",
    "name": "Aldrich Chen",
    "url": "https://aldrich.fyi"
  }},
  "description": "Daily edition: {d['total']} China-background hardware projects tracked · {counts['prelaunch']} prelaunch · {counts['live']} live ({fmt_usd(d['total_live_usd'])})."
}}
</script>

<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=JetBrains+Mono:wght@500;700&family=Playfair+Display:ital,wght@0,700;0,900;1,700&family=Lora:ital,wght@0,400;1,400&display=swap');
</style></head>
<body style="margin:0;padding:24px 12px;background:{PAPER};
             background-image:url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='4' height='4'%3E%3Cpath fill='%23111111' fill-opacity='0.05' d='M1 3h1v1H1V3zm2-2h1v1H3V1z'/%3E%3C/svg%3E\");
             font-family:{BODY};color:{INK};line-height:1.6">

<!-- Preheader: inbox preview text. Hidden visually, read by Gmail/Apple Mail/Outlook
     to populate the gray summary line under the subject in the inbox list.
     The &zwnj;&nbsp; padding pushes other body content out of the preview. -->
<div style="display:none;max-height:0;overflow:hidden;font-size:1px;line-height:1px;color:transparent;mso-hide:all;opacity:0">
{_esc(preheader_text)}
&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;
&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;
</div>

<table role="presentation" cellspacing="0" cellpadding="0" border="0"
       style="max-width:680px;margin:0 auto;background:{PAPER};
              border-left:1px solid {INK};border-right:1px solid {INK}">
  <tr>
    <td style="padding:0">

      <!-- Edition strip -->
      <div style="background:{INK};color:{PAPER};padding:10px 28px;
                  font-family:{SANS};font-size:10px;font-weight:700;
                  letter-spacing:2.5px;display:flex;justify-content:space-between;
                  align-items:center;flex-wrap:wrap;gap:8px">
        <span>
          <span style="display:inline-block;width:6px;height:6px;background:{RED};
                       margin-right:8px;vertical-align:1px"></span>
          DAILY · LIVE EDITION · {today_long}
        </span>
        <span style="font-family:{MONO};font-weight:500">VOL. 1 · NO. {edition} ·
          <a href="https://chen17-sq.github.io/kickstarter-china-tracker/editions/{today}.pdf"
             style="color:{PAPER};text-decoration:none;
             border-bottom:1px solid {RED};padding-bottom:1px;margin-left:6px">↓ PDF</a>
        </span>
      </div>

      <!-- Masthead -->
      <div style="padding:38px 28px 22px;border-bottom:4px solid {INK};text-align:center">
        <h1 style="margin:0;font-family:{SERIF};font-weight:900;
                   font-size:54px;line-height:.95;letter-spacing:-2px;color:{INK}">Kickstarter China Tracker</h1>
        <div style="margin-top:16px;border-top:1px solid {INK};border-bottom:1px solid {INK};
                    padding:6px 0;display:flex;justify-content:space-between;
                    font-family:{MONO};font-size:10.5px;font-weight:500;
                    letter-spacing:2px;text-transform:uppercase;color:{INK}">
          <span style="padding:0 4px">BEIJING EDITION</span>
          <span style="font-family:{SERIF};font-weight:400;font-style:italic;
                       letter-spacing:0;text-transform:none;font-size:13px">
            All The Crowd-Funded Hardware Fit To Print
          </span>
          <span style="padding:0 4px">PLEDGED · {fmt_usd(d['total_live_usd'])}</span>
        </div>
        <p style="margin:18px auto 0;max-width:50ch;font-family:{BODY};font-style:italic;
                  font-size:14.5px;color:{N700};line-height:1.5">
          每日追踪 Kickstarter 上中国背景的消费硬件项目 · pre-launch · live · 已结束
        </p>
      </div>

      <!-- Emergency refresh banner (only renders if today's snapshot
           came from scripts/emergency_refresh.py) -->
      <div style="padding:0 28px">
        {_render_emergency_banner(curr)}
      </div>

      <!-- Lede paragraph with drop cap -->
      <div style="padding:28px 28px 8px">
        <span style="float:left;font-family:{SERIF};font-weight:900;font-size:64px;
                     line-height:.85;color:{INK};margin:6px 10px 0 0">今</span>
        <p style="margin:0;font-family:{BODY};font-size:15px;line-height:1.7;
                  color:{INK};text-align:justify">{lede_text}</p>
        <div style="clear:both"></div>
      </div>

      <!-- KPI band -->
      <table role="presentation" cellspacing="0" cellpadding="0" border="0"
             style="width:100%;margin-top:24px;border-top:4px solid {INK};
                    border-bottom:4px solid {INK};border-collapse:collapse">
        <tr>
          {_kpi_cell("TRACKED", str(d['total']))}
          {_kpi_cell("PRELAUNCH", str(counts['prelaunch']), RED)}
          {_kpi_cell("LIVE", str(counts['live']))}
          {_kpi_cell("FUNDED", str(counts['successful']))}
          {_kpi_cell("EDITOR'S", f"★ {d['pwl']}", last=True)}
        </tr>
      </table>

      <div style="padding:0 28px">

        <!-- Prelaunch section · Top 10 (Top 3 detail + 4-10 list) -->
        <div style="margin-top:48px">
          <div style="font-family:{MONO};font-size:11px;font-weight:500;color:{N500};
                      letter-spacing:2.5px;margin-bottom:6px">SECTION A</div>
          <h2 style="margin:0 0 4px;font-family:{SERIF};font-weight:900;font-size:28px;
                     letter-spacing:-.5px;color:{INK}">⏳ Prelaunch · Top 10</h2>
          <p style="margin:0 0 4px;font-family:{BODY};font-style:italic;font-size:13px;color:{N500}">
            按关注数排序 · KS Editor's Picks 优先 · Top 3 含图文亮点 · 4–10 列表形式
          </p>
          <div style="border-top:4px solid {INK}">
            {pre_detail or '<p style="padding:14px 0;color:'+N400+'">暂无</p>'}
          </div>
          {pre_rest_html}
        </div>

        <!-- Live section · Top 10 (Top 3 detail + 4-10 list) -->
        <div style="margin-top:48px">
          <div style="font-family:{MONO};font-size:11px;font-weight:500;color:{N500};
                      letter-spacing:2.5px;margin-bottom:6px">SECTION B</div>
          <h2 style="margin:0 0 4px;font-family:{SERIF};font-weight:900;font-size:28px;
                     letter-spacing:-.5px;color:{INK}">🔴 Live · Top 10 by USD Raised</h2>
          <p style="margin:0 0 4px;font-family:{BODY};font-style:italic;font-size:13px;color:{N500}">
            按已筹排序 · {counts['live']} 个 live 项目 · Top 3 含图文亮点 · 4–10 列表形式
          </p>
          <div style="border-top:4px solid {INK}">
            {live_detail or '<p style="padding:14px 0;color:'+N400+'">暂无</p>'}
          </div>
          {live_rest_html}
        </div>

        {sleepers_html}

        {_render_editor_drafts_beta(_load_editor_drafts())}

        <!-- Ornament -->
        <div style="padding:40px 0 16px;text-align:center;
                    font-family:{SERIF};font-size:20px;color:{N400};letter-spacing:14px">
          ✦ &nbsp; ✦ &nbsp; ✦
        </div>

        <!-- Footer -->
        <div style="border-top:4px solid {INK};padding:22px 0 32px;
                    font-family:{MONO};font-size:10.5px;color:{N500};
                    letter-spacing:1.5px;text-transform:uppercase">
          <a href="{PAGES_URL}" style="color:{INK};text-decoration:none;
              border-bottom:2px solid {RED};padding-bottom:1px;font-weight:700">FULL PAPER</a>
          &nbsp;·&nbsp;
          <a href="{LATEST_URL}" style="color:{INK};text-decoration:none;
              border-bottom:2px solid {RED};padding-bottom:1px;font-weight:700">LATEST REPORT</a>
          &nbsp;·&nbsp;
          <a href="https://github.com/Chen17-sq/kickstarter-china-tracker"
             style="color:{INK};text-decoration:none;border-bottom:2px solid {RED};
             padding-bottom:1px;font-weight:700">GITHUB</a>
          <div style="margin-top:14px;font-family:{SERIF};font-style:italic;
                      font-size:13px;color:{N500};letter-spacing:0;text-transform:none">
            All the news that's fit to print, every morning at 08:00 Beijing.
          </div>
          <div style="margin-top:10px;font-size:10px">
            退订 · 在仓库 SETTINGS → SECRETS → ACTIONS 把 NOTIFY_EMAIL_TO 删掉
          </div>
        </div>

      </div>
    </td>
  </tr>
</table>

</body>
</html>'''


def post_resend(api_key: str, sender: str, to: list[str], subject: str,
                html: str, text: str | None = None,
                max_retries: int = 3) -> None:
    """POST to Resend. If `text` is provided, the email is sent as
    multipart with both HTML and plaintext alternatives — better for spam
    scores, accessibility (screen readers), and clients that prefer text.

    Auto-retries on 429 (Resend free tier limits to 5 req/s). Respects
    the Retry-After header when present, otherwise backs off exponentially
    (1s, 2s, 4s). Raises after `max_retries` 429s in a row — at that
    point the rate limit is structural and the caller should be told.
    """
    payload = {"from": sender, "to": to, "subject": subject, "html": html}
    if text:
        payload["text"] = text
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    for attempt in range(max_retries):
        resp = httpx.post(RESEND_API_URL, headers=headers, json=payload, timeout=30)
        if resp.status_code == 429:
            # Prefer server-provided Retry-After, fall back to exponential.
            ra = resp.headers.get("retry-after", "")
            try:
                wait = float(ra) if ra else 2.0 ** attempt
            except ValueError:
                wait = 2.0 ** attempt
            wait = min(max(wait, 0.5), 10.0)
            if attempt < max_retries - 1:
                time.sleep(wait)
                continue
        if resp.status_code >= 400:
            print(f"Resend error {resp.status_code}: {resp.text}", file=sys.stderr)
            resp.raise_for_status()
        return


def build_plaintext(curr: dict) -> str:
    """Generate a plaintext alternative for the daily edition.

    Sent alongside the HTML body in a multipart message. Improves spam
    scoring (mail filters expect a text part), enables accessibility for
    screen readers, and gives terminal/text-mode clients (Mutt, etc.) a
    usable read.

    Format mirrors the HTML structure: masthead, KPI line, Top 10 prelaunch,
    Top 10 live, links to the visual + Atom feed. No images, no styling,
    no tables — just structured text with separators.
    """
    d = get_summary_data(curr)
    today = d["today"]
    counts = d["counts"]
    edition = edition_number()
    lines: list[str] = []
    rule = "─" * 60

    lines.append("KICKSTARTER CHINA TRACKER")
    lines.append(f"Vol. 1, No. {edition} · {today}")
    lines.append("All The Crowd-Funded Hardware Fit To Print.")
    lines.append("")
    lines.append(rule)
    lines.append(
        f"{d['total']} 项追踪 · {counts['prelaunch']} prelaunch · "
        f"{counts['live']} live ({fmt_usd(d['total_live_usd'])}) · "
        f"{counts['successful']} successful · ✦ KS Pick {d['pwl']}"
    )
    lines.append(rule)
    lines.append("")

    pre = d["prelaunch"][:10]
    if pre:
        lines.append("⏳ PRELAUNCH · TOP 10 BY FOLLOWERS")
        lines.append("")
        for i, p in enumerate(pre, 1):
            star = "★ " if p.get("project_we_love") else "  "
            title = (p.get("title") or "?")[:50]
            zh = p.get("blurb_zh") or ""
            lines.append(f"{i:2d}. {star}{title}")
            if zh:
                lines.append(f"      {zh[:60]}")
            lines.append(f"      {fmt_int(p.get('followers') or 0)} followers")
            url = p.get("url")
            if url:
                lines.append(f"      {url}")
            lines.append("")

    live = d["live"][:10]
    if live:
        lines.append("🔴 LIVE · TOP 10 BY USD RAISED")
        lines.append("")
        for i, p in enumerate(live, 1):
            star = "★ " if p.get("project_we_love") else "  "
            title = (p.get("title") or "?")[:50]
            zh = p.get("blurb_zh") or ""
            lines.append(f"{i:2d}. {star}{title}")
            if zh:
                lines.append(f"      {zh[:60]}")
            lines.append(
                f"      {fmt_usd(p.get('pledged_usd'))} · "
                f"{fmt_int(p.get('backers') or 0)} backers"
            )
            url = p.get("url")
            if url:
                lines.append(f"      {url}")
            lines.append("")

    lines.append(rule)
    lines.append("VIEW VISUAL · https://ks.aldrich.fyi/editions/latest.html")
    lines.append("RSS FEED    · https://ks.aldrich.fyi/feed.xml")
    lines.append("ARCHIVE     · https://ks.aldrich.fyi/editions/")
    lines.append("")
    lines.append("─ ✦ ─")
    lines.append("Reply 'unsubscribe' to stop receiving these.")

    return "\n".join(lines)


def write_archive(html: str) -> None:
    """Save today's HTML edition to site/editions/ + rebuild the index page.

    Pages URL pattern:
      https://chen17-sq.github.io/kickstarter-china-tracker/editions/
      https://chen17-sq.github.io/kickstarter-china-tracker/editions/2026-04-26.html
      https://chen17-sq.github.io/kickstarter-china-tracker/editions/latest.html
    """
    today = dt.datetime.now(dt.UTC).strftime("%Y-%m-%d")
    out_dir = REPO_ROOT / "site" / "editions"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{today}.html").write_text(html, encoding="utf-8")
    (out_dir / "latest.html").write_text(html, encoding="utf-8")
    # Rebuild the directory index from disk so it always matches the file list
    _write_editions_index(out_dir)


def _write_editions_index(out_dir: Path) -> None:
    """Generate site/editions/index.html — a Newsprint-styled archive list."""
    dated = sorted(
        (f.stem for f in out_dir.glob("*.html") if f.stem not in ("latest", "index")),
        reverse=True,
    )
    rows = []
    for stem in dated:
        try:
            d = dt.datetime.strptime(stem, "%Y-%m-%d")
            label = d.strftime("%A · %B %d, %Y")
            edition = (d - dt.datetime(2026, 4, 25)).days + 1
        except ValueError:
            label = stem
            edition = "—"
        rows.append(
            f'<li style="display:flex;justify-content:space-between;align-items:baseline;'
            f'padding:14px 0;border-bottom:1px solid {INK}">'
            f'<a href="./{stem}.html" style="font-family:{SERIF};font-weight:700;'
            f'font-size:20px;color:{INK};text-decoration:none">{label}</a>'
            f'<span style="font-family:{MONO};font-size:11px;color:{N500};'
            f'letter-spacing:.18em">VOL. 1 · NO. {edition}</span>'
            f'</li>'
        )
    items = "".join(rows) or (
        f'<li style="font-family:{BODY};font-style:italic;color:{N500};'
        f'padding:24px 0">No editions archived yet — first one ships tomorrow.</li>'
    )

    page = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head><meta charset="UTF-8"><title>Editions · Kickstarter China Tracker</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&family=Playfair+Display:ital,wght@0,400;0,600;0,700;0,900;1,400;1,700&family=Lora:ital,wght@0,400;0,600;1,400&display=swap" rel="stylesheet">
<style>
*{{box-sizing:border-box;border-radius:0!important}}
body{{margin:0;padding:0;background:{PAPER};color:{INK};font-family:{BODY};font-size:15px;line-height:1.625;
  background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='4' height='4'%3E%3Cpath fill='%23111111' fill-opacity='0.05' d='M1 3h1v1H1V3zm2-2h1v1H3V1z'/%3E%3C/svg%3E")}}
.wrap{{max-width:840px;margin:0 auto;background:{PAPER};border-left:1px solid {INK};border-right:1px solid {INK};min-height:100vh}}
.strip{{display:flex;justify-content:space-between;padding:8px 28px;background:{INK};color:{PAPER};
  font-family:{SANS};font-size:10.5px;font-weight:600;letter-spacing:.2em;text-transform:uppercase}}
.strip .dot{{display:inline-block;width:6px;height:6px;background:{RED};margin-right:8px;vertical-align:1px}}
.mast{{padding:36px 28px 22px;border-bottom:4px solid {INK};text-align:center}}
.mast h1{{margin:0;font-family:{SERIF};font-weight:900;font-size:42px;line-height:.95;
  letter-spacing:-1.2px;color:{INK}}}
.mast .tag{{display:flex;justify-content:space-between;border-top:1px solid {INK};
  border-bottom:1px solid {INK};padding:8px 0;margin-top:14px;
  font-family:{MONO};font-size:11px;letter-spacing:.18em;text-transform:uppercase;font-weight:500}}
.mast .center{{flex:1;text-align:center;font-style:italic;letter-spacing:0;
  font-family:{SERIF};font-size:13px;font-weight:400;text-transform:none}}
.section-h{{padding:28px 28px 12px;border-bottom:1px solid {INK}}}
.section-h .label{{font-family:{MONO};font-size:11px;letter-spacing:2.5px;color:{N500}}}
.section-h h2{{margin:6px 0 0;font-family:{SERIF};font-weight:900;font-size:32px;
  letter-spacing:-1px;color:{INK}}}
ul{{list-style:none;margin:0;padding:0 28px}}
.foot{{margin-top:auto;padding:24px 28px 36px;border-top:4px solid {INK};
  font-family:{MONO};font-size:10.5px;color:{N500};letter-spacing:.1em;text-transform:uppercase;text-align:center}}
.foot a{{color:{INK};text-decoration:none;border-bottom:2px solid {RED};padding-bottom:1px;font-weight:700}}
@media (max-width:680px){{
  .wrap{{border:0}}
  .mast h1{{font-size:30px}}
  .mast .tag{{flex-direction:column;gap:4px}}
}}
</style></head>
<body><div class="wrap">
<div class="strip"><span><span class="dot"></span>EDITIONS · 永久存档</span><span style="font-family:{MONO};letter-spacing:.18em">{len(dated)} ISSUES</span></div>
<header class="mast">
  <h1>Kickstarter China Tracker</h1>
  <div class="tag">
    <span style="padding:0 14px">Editions Archive</span>
    <span class="center">All The Crowd-Funded Hardware Fit To Print</span>
    <span style="padding:0 14px">{len(dated)} 期已发刊</span>
  </div>
</header>
<div class="section-h">
  <div class="label">SECTION · BACK ISSUES</div>
  <h2>过往日报 · Daily Editions</h2>
</div>
<ul>{items}</ul>
<footer class="foot">
  <a href="../">完整看板</a> &nbsp;·&nbsp;
  <a href="../subscribe.html">订阅</a> &nbsp;·&nbsp;
  <a href="../stats.html">公开数据</a> &nbsp;·&nbsp;
  <a href="https://github.com/Chen17-sq/kickstarter-china-tracker">GitHub</a>
</footer>
</div></body></html>"""
    (out_dir / "index.html").write_text(page, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true",
                    help="Build the email, write a preview HTML, no POST.")
    args = ap.parse_args(argv)

    if not PROJECTS.exists():
        print("data/projects.json not found", file=sys.stderr)
        return 1
    curr = json.loads(PROJECTS.read_text(encoding="utf-8"))
    subject, html = build_html(curr)
    # Build plaintext alt for multipart messages — better spam scoring,
    # accessibility, and terminal-client legibility.
    plain_text = build_plaintext(curr)

    # Always archive — even on dry-run / no-API-key — so Pages always has the
    # latest visual edition viewable at /editions/<date>.html.
    write_archive(html)

    if args.dry_run:
        preview = REPO_ROOT / "data" / ".tmp" / "email_preview.html"
        preview.parent.mkdir(parents=True, exist_ok=True)
        preview.write_text(html, encoding="utf-8")
        print(f"Subject: {subject}")
        print(f"HTML: {len(html):,} chars")
        print(f"Preview: file://{preview}")
        return 0

    api_key = os.environ.get("RESEND_API_KEY")
    if not api_key:
        print("RESEND_API_KEY not set — email skipped")
        return 0

    raw_to = os.environ.get("NOTIFY_EMAIL_TO", "")
    to_owner = [e.strip() for e in raw_to.split(",") if e.strip()]

    # Subscriber broadcast: enabled by default. Set BROADCAST=0 to disable.
    # Each subscriber is sent the email separately so unsubscribe / bounce
    # tracking is per-recipient. Resend sandbox will reject unverified
    # recipients (422) — we print + continue rather than abort the run.
    broadcast = os.environ.get("BROADCAST", "1") != "0"
    sub_emails: list[str] = []
    if broadcast:
        try:
            from .subscribers import emails as load_subscriber_emails
            sub_emails = load_subscriber_emails()
        except Exception as e:
            print(f"  warn: subscribers load failed ({e}); broadcast off")
            sub_emails = []

    # Dedupe: subscribers union owner addresses.
    seen = set(e.lower() for e in to_owner)
    recipients = list(to_owner)
    for s in sub_emails:
        if s.lower() not in seen:
            recipients.append(s)
            seen.add(s.lower())

    if not recipients:
        print("No recipients (NOTIFY_EMAIL_TO empty + no subscribers) — skipping")
        return 0

    sender = (os.environ.get("NOTIFY_EMAIL_FROM") or
              "KS China Tracker <onboarding@resend.dev>")

    # ── Last-gate sanity check before broadcast ───────────────────────
    # Loads previous snapshot from history (one before today's), runs the
    # quality gate. If it fails, broadcast is BLOCKED — owner gets a
    # plaintext alert email; subscribers get nothing.
    from .report import find_prev_snapshot
    from .sanity import format_alert_body, validate_for_send
    prev_snapshot = find_prev_snapshot()
    ok, issues = validate_for_send(curr, prev_snapshot)
    if issues:
        print("⚠ sanity issues:")
        for i in issues:
            print(f"  - {i}")
    if not ok:
        print(f"⚠ BROADCAST BLOCKED — alerting owner only ({to_owner})")
        if to_owner:
            alert_body = format_alert_body(issues, curr)
            alert_html = (
                f'<pre style="font-family:monospace;font-size:13px;white-space:pre-wrap">'
                f'{_esc(alert_body)}</pre>'
            )
            alert_subj = f"[ALERT] KS Tracker broadcast BLOCKED · {dt.datetime.now(dt.UTC).strftime('%Y-%m-%d')}"
            for owner in to_owner:
                try:
                    post_resend(api_key, sender, [owner], alert_subj, alert_html)
                    print(f"  → alert sent to {owner}")
                except Exception as e:
                    print(f"  ! alert to {owner} failed: {e}", file=sys.stderr)
        return 0

    # Build a creator → personalised banner map ahead of the broadcast loop.
    # If a subscriber has type="creator" + a creator_slug that matches any
    # project in today's snapshot, we prepend a banner to their copy of the
    # email greeting them by name and showing where their projects landed.
    creator_banners: dict[str, str] = {}
    try:
        from .subscribers import all_subscribers
        all_subs = all_subscribers()
    except Exception as e:
        print(f"  warn: all_subscribers load failed ({e})")
        all_subs = []
    if all_subs:
        # Map creator_slug → list of their projects in today's data
        slug_to_projects: dict[str, list[dict]] = {}
        for p in (curr.get("projects") or []):
            cs = p.get("creator_slug")
            if cs:
                slug_to_projects.setdefault(cs, []).append(p)
        for sub in all_subs:
            if sub.get("type") != "creator":
                continue
            slug = sub.get("creator_slug")
            if not slug:
                continue
            mine = slug_to_projects.get(slug) or []
            if not mine:
                continue  # nothing of theirs in today's edition; standard email
            email_addr = (sub.get("email") or "").lower()
            nick = _esc(sub.get("nickname") or slug)
            # Sort the creator's projects by status (live > prelaunch > successful)
            order = {"live": 0, "prelaunch": 1, "successful": 2}
            mine_sorted = sorted(mine, key=lambda p: order.get(p.get("status", ""), 9))
            rows = []
            for p in mine_sorted[:3]:
                title = _esc(p.get("title") or "(untitled)")
                status = _esc(p.get("status") or "")
                metric = ""
                if p.get("status") == "live":
                    metric = f"{fmt_usd(p.get('pledged_usd'))} · {fmt_int(p.get('backers'))} backers"
                elif p.get("status") == "prelaunch":
                    metric = f"{fmt_int(p.get('followers'))} watchers"
                elif p.get("status") == "successful":
                    metric = f"funded · {fmt_usd(p.get('pledged_usd'))}"
                rows.append(
                    f'<li style="margin:5px 0;font-family:{BODY};font-size:13.5px;'
                    f'color:{INK};list-style:none;padding-left:14px;position:relative">'
                    f'<span style="position:absolute;left:0;color:{RED};font-weight:900">▸</span>'
                    f'<span style="font-family:{SERIF};font-weight:700">{title}</span> '
                    f'<span style="color:{N500};font-family:{MONO};font-size:11px;'
                    f'letter-spacing:.06em">[{status}] {metric}</span></li>'
                )
            banner = f'''
            <div style="margin:24px 28px 0;padding:18px 22px;border:2px solid {RED};
                        background:{PAPER}">
              <div style="font-family:{SANS};font-size:9.5px;font-weight:700;
                   letter-spacing:.25em;color:{RED};text-transform:uppercase;margin-bottom:6px">
                FOR YOU · CREATOR'S CORNER
              </div>
              <p style="margin:0 0 8px;font-family:{SERIF};font-size:18px;font-weight:700;
                 color:{INK};line-height:1.3">
                Hey {nick} — your project{'s' if len(mine_sorted) > 1 else ''} in today's edition:
              </p>
              <ul style="margin:8px 0 0;padding:0">{''.join(rows)}</ul>
              <p style="margin:10px 0 0;font-family:{BODY};font-style:italic;font-size:12.5px;
                 color:{N600};line-height:1.45">
                Below is the same edition every other reader gets — but starting from
                today, you'll see your projects flagged at the top whenever they show
                up on the radar.
              </p>
            </div>'''
            creator_banners[email_addr] = banner

    # Robust regex for injecting after <body ...> — handles any attribute form
    import re as _re
    BODY_OPEN_RE = _re.compile(r'(<body\b[^>]*>)', _re.IGNORECASE)

    sent = 0
    failed = 0
    failure_log: list[str] = []  # for owner digest
    for r in recipients:
        banner = creator_banners.get(r.lower())
        html_for_this = html
        if banner:
            # Inject creator banner immediately after the <body ...> tag.
            # Using regex so any whitespace / attribute order in <body> works.
            new_html, n = BODY_OPEN_RE.subn(r"\1" + banner, html, count=1)
            if n == 1:
                html_for_this = new_html
            else:
                # Fall back to standard email if injection markers shift —
                # better to send unbranded than to send broken HTML.
                print(f"  ! creator banner inject FAILED for {r}; sending standard", file=sys.stderr)
                html_for_this = html
        try:
            post_resend(api_key, sender, [r], subject, html_for_this, text=plain_text)
            sent += 1
        except Exception as e:
            # Most likely cause in sandbox mode: 422 'You can only send testing
            # emails to your own email address'. Don't fail the cron — the
            # owner email is always first in the list and almost always works.
            print(f"  ! send to {r} failed: {e}", file=sys.stderr)
            failed += 1
            failure_log.append(f"{r}: {str(e)[:200]}")
        # Resend free tier caps at 5 req/s. Pace at ~4/s to leave headroom
        # for the owner-digest send that follows the loop; post_resend's
        # 429-retry handles bursts above that, but pacing avoids triggering
        # the retry path on every recipient when the list grows.
        time.sleep(0.25)
    print(f"Email broadcast: sent={sent}, failed={failed}, "
          f"creator_personalised={len(creator_banners)}, from={sender}")

    # ── Owner daily digest ────────────────────────────────────────
    # Even on full success, send a separate plaintext "operations digest"
    # to the owner. This is the observability layer — owner gets one
    # email per day saying exactly what ran and what was sent. Catches
    # silent degradation, silent partial failures, drift over time.
    # (Skipped if there's no owner email or alert was already sent.)
    if to_owner:
        # Scrape health (curl_cffi vs playwright path, coverage %) read
        # from data/.scrape_health.json. Owner sees fallback usage trend
        # over time — catches "still working but degrading" creep.
        from . import health as _health
        _health_state = _health.load()
        # `d` / `counts` are bound inside build_html(); recompute the
        # summary here so the digest can render. Cheap (pure dict scan).
        digest_d = get_summary_data(curr)
        digest_counts = digest_d["counts"]
        digest_subj = (
            f"[OPS] KS Tracker · {dt.datetime.now(dt.UTC).strftime('%Y-%m-%d')} · "
            f"sent={sent} failed={failed}"
        )
        digest_lines = [
            "Daily KS Tracker run completed.",
            "",
            "Snapshot:",
            f"  generated_at:   {curr.get('generated_at','—')}",
            f"  total projects: {digest_d.get('total','?')}",
            f"  prelaunch:      {digest_counts.get('prelaunch','?')}",
            f"  live:           {digest_counts.get('live','?')}",
            f"  successful:     {digest_counts.get('successful','?')}",
            f"  pledged USD:    {fmt_usd(digest_d.get('total_live_usd', 0))}",
            f"  high confidence: {digest_d.get('high','?')}",
            f"  ✦ KS picks:     {digest_d.get('pwl','?')}",
            "",
            "Broadcast:",
            f"  recipients (deduped):  {len(recipients)}",
            f"  sent successfully:     {sent}",
            f"  failed:                {failed}",
            f"  sender:                {sender}",
        ]
        if _health_state:
            digest_lines.append("")
            digest_lines.extend(_health.format_digest_lines(_health_state))
        # Per-project anomalies (vanished/reverted/stuck) — FYI in digest.
        try:
            from . import anomalies as _anomalies_mod
            _anomalies_state = _anomalies_mod.load()
            anomaly_lines = _anomalies_mod.format_digest_lines(_anomalies_state)
            if anomaly_lines:
                digest_lines.append("")
                digest_lines.extend(anomaly_lines)
        except Exception:
            pass
        # Brand candidates — unknown creators with high signals worth review.
        try:
            from . import brand_candidates as _bc_mod
            _bc_state = _bc_mod.load()
            bc_lines = _bc_mod.format_digest_lines(_bc_state)
            if bc_lines:
                digest_lines.append("")
                digest_lines.extend(bc_lines)
        except Exception:
            pass
        # Tier metrics — last 7 days of which transport tier carried
        # each fetch path. Used to spot CF pattern shifts (e.g. "Tier 1
        # has been failing 6/7 days; CF must've fingerprinted curl_cffi").
        try:
            from . import tier_metrics as _tm
            tm_lines = _tm.format_digest_lines(window_days=7)
            if tm_lines:
                digest_lines.append("")
                digest_lines.extend(tm_lines)
        except Exception:
            pass
        if failure_log:
            digest_lines.append("")
            digest_lines.append("Failures:")
            for f in failure_log:
                digest_lines.append(f"  - {f}")
        if issues:
            digest_lines.append("")
            digest_lines.append("Sanity warnings (informational, broadcast still went out):")
            for i in issues:
                digest_lines.append(f"  - {i}")
        digest_lines += [
            "",
            "Live: https://ks.aldrich.fyi/",
            f"This edition: https://ks.aldrich.fyi/editions/{dt.datetime.now(dt.UTC).strftime('%Y-%m-%d')}.html",
            "",
            "— ops digest, scraper/email_notify.py",
        ]
        digest_body = "\n".join(digest_lines)
        digest_html = (
            f'<pre style="font-family:monospace;font-size:12px;'
            f'white-space:pre-wrap;line-height:1.5">{_esc(digest_body)}</pre>'
        )
        for owner in to_owner:
            try:
                post_resend(api_key, sender, [owner], digest_subj, digest_html)
            except Exception as e:
                print(f"  ! ops digest to {owner} failed: {e}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
